CREATE TABLE IF NOT EXISTS js_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  section TEXT CHECK(section IN ('public', 'admin')) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
