CREATE TABLE IF NOT EXISTS kpi_mensili (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mese TEXT NOT NULL, -- formato YYYY-MM
  vendite INTEGER DEFAULT 0,
  nuovi_utenti INTEGER DEFAULT 0,
  feedback INTEGER DEFAULT 0,
  revenue REAL DEFAULT 0
);
