CREATE TABLE IF NOT EXISTS tutorial (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  titolo TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  categoria TEXT,
  testo TEXT,
  steps TEXT,
  video_url TEXT,
  prodotto_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
